name = "raspy-glade-355f"
compatibility_date = "2026-03-05"
main = "src/worker.js"

routes = [
  { pattern = "neonarcade.net/*", zone_name = "neonarcade.net" }
]

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "GAME_DATA"
id = "1a83accd339440ebab05563fea7335e0"
